name: Daily scraper of CISA KEV json

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Scrape CISA KEV
        run: curl -f --silent --output known_exploited_vulnerabilities.json https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json

      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated daily update"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Update json: ${timestamp}" || exit 0
          git push
